### ISSUE TITLE
Discussion: how can we get jobs on the jobboard

### ISSUE THREAD

**Issue by pascaldevink** [AmsterdamPHP/job-board#1]
Or in other words, how to filter the shit and actually get only jobs on the board. And preferably _good_ jobs. That might mean we must first define what we mean with _good_ jobs.

Also, from whom will these jobs come? Will it be possible for anybody to suggest a job opening, or will there be a account required? Is anybody allowed to register, or will this be moderated?

Personally, I don't think any of us has the time nor interest in moderating a job board like this full-time. So my preference would be to take the Google-approach: allow all, until complains start coming in and let the users rank the job openings and perhaps even the person/company posting the job opening. This way. the aforementioned shit will most likely not hit the surface.

What are other thoughts about this subject?

**Comment by francodacosta** [comment]
I like your idea, a simple "flag this job posting" should be enough in the beginning later on we can rate and share our experience dealing with a recruiter

**Comment by rdohms** [comment]
I agree, force registration since that reduces the bot spam a bit and allows us to rate users according to how many "reports" they get, then we can block the whole account.

But start simple, force registration and add a "flag this" and "up, down". This will give us enough data to evolve later.
