### ISSUE TITLE
Instant 3 point average

### ISSUE THREAD

**Issue by rdohms** [AmsterdamPHP/job-board#18]
Just created a fresh post and it instantly had a 3 star rating.

It should have no rating at all.

![Screen Shot 2013-04-26 at 15 55 30 ](https://f.cloud.github.com/assets/94331/430868/ffe827f8-ae78-11e2-9ed6-bf1692c5f37a.png)

**Comment by pascaldevink** [comment]
The default nullable calculatedRating field was the problem. Although the deeper problem lies within the rateIt jQuery plugin, which apparently defaults to 3 if no value is given, but that goed beyond the scope for now.
