### ISSUE TITLE
Discussion: only Amsterdam area

### ISSUE THREAD

**Issue by pascaldevink** [AmsterdamPHP/job-board#2]
Once online, will it be possible to create job openings for the entire nation, or perhaps even the entire world, or just the greater Amsterdam area?

Personally, I wouldn't mind worldwide job openings, but I think there should be certain restrictions to this, such as:
1. Poster/company is aware that many respondents will apply from The Netherlands and must be willing to support them with moving to the new country.
2. It must be very clear for the respondent that the job opening is for a job in another country.
3. Job openings should only be posted in English.

**Comment by francodacosta** [comment]
I'm in favour of job openings for the entire country.

I agree with the criteria for worldwide jobs

I think all job postings should be in English, and they should accept English speaking candidates (Dutch should not be a prerequisite)

**Comment by rdohms** [comment]
I'm against opening for the whole country.

AmsterdamPHP is a group for Amsterdam, we should not overstep our boundaries as it will bring more work and i'm not looking to manage a Worldwide PHP job board, that will become too much trouble very fast.

Can we use this software and load up a new board on a world level, sure, but we need to roll out a Amsterdam board.

Yes, all job announcements should be in english as the group is a english speaking group. Jobs may require dutch, but that should also be a clear flag so we can search by it.
