### ISSUE TITLE
Report does not send emails

### ISSUE THREAD

**Issue by rdohms** [AmsterdamPHP/job-board#24]
I did not get and email after reporting a job ad.
Also i do not see them listed on the page.

**Comment by rdohms** [comment]
Checking server configuration and disabling spooling.

**Comment by pascaldevink** [comment]
I now get "InvalidTypeException: Invalid type for path "swiftmailer.spool". Expected array, but got boolean" on each pageload.

**Comment by rdohms** [comment]
Crap, i hate undocumented stuff, let me patch this.
