### ISSUE TITLE
[Front end] [enhancement] Adjustments for Mobile

### ISSUE THREAD

**Issue by erikaheidi** [AmsterdamPHP/job-board#25]
Here are 2 screenshots taken with my Samsung Galaxy S. I will try also with another devices soon and post screenshots here.
![Screenshot_2013-04-26-16-13-10](https://f.cloud.github.com/assets/293241/430997/c8ac9a22-ae7c-11e2-8409-c81a6866b4d8.png)
![Screenshot_2013-04-26-16-14-16](https://f.cloud.github.com/assets/293241/430998/c8afbb9e-ae7c-11e2-9acd-c7987dc0683e.png)

I guess we can remove some padding / spacing. I can help with something this weekend.

**Comment by pascaldevink** [comment]
I think I fixed this in https://github.com/AmsterdamPHP/job-board/commit/7f187e1154de8a23fe10c7a4249e7700397a9120.
I made the top navigation be fixed on mobile devices and thereby made it broader, so the text gets more space.

![iOS Simulator Screen shot Apr 29 2013 2 59 18 PM](https://f.cloud.github.com/assets/106844/438514/a723f95c-b0cc-11e2-9adb-8a36db85fe3d.png)
