### ISSUE TITLE
[Frontend][Mobile] Odd character between timestamp and rating

### ISSUE THREAD

**Issue by WyriHaximus** [AmsterdamPHP/job-board#27]
Noticed it on my HTC Desire S, not sure yet what's causing it but will investigate and fix it over the weekend.
![2013-04-26_16-09-12](https://f.cloud.github.com/assets/147145/431148/2e88d62c-ae81-11e2-9e11-519189dd019e.jpg)

**Comment by WyriHaximus** [comment]
After some digging around I found out it's a Android 2.3 stock browser bug occurring when an inline-block element is  used within a `h{1,2,3,4,5,6}` tag.  I'm working on a solution with the least impossible.

**Comment by pascaldevink** [comment]
I've changed the markup of that area, does it still occur? Note: these changes aren't live yet.

**Comment by WyriHaximus** [comment]
Nope you fixed it :). 

![](http://i.imgur.com/61FpHIb.jpeg)
