### ISSUE TITLE
WYSIWYG Editor for job posts

### ISSUE THREAD

**Issue by rdohms** [AmsterdamPHP/job-board#36]
Usage tests have shown that some sort of WYSIWYG editor needs to be put in place.

Important:
- Should be a simple editor, simple install, symfony bundle, etc.
- Input filtering should be added, DMS Filter Bundle can provide the needed tools for this.

**Comment by pascaldevink** [comment]
I know there was a discussion last week on IRC, but I can't remember if we picked a good editor?

**Comment by rdohms** [comment]
The only decisions made were the above criteria, which tends to points the traditional ones which are the easiest to install and have bundles and etc.
