### ISSUE TITLE
Broken after 5.5 upgrade

### ISSUE THREAD

**Issue by rdohms** [AmsterdamPHP/job-board#49]
May be totally unrelated, but after upgrading the server to 5.5 the site broke.

**Comment by pascaldevink** [comment]
Any pointers as to where it breaks?

**Comment by rdohms** [comment]
In that big blank white screen...

I have no clue, but the logs seem like a good start.

**Comment by rdohms** [comment]
Fixed with a cache:clear :tada:

**Comment by pascaldevink** [comment]
Jeeeej! :sweat_smile: :beers:
